### PR TITLE
nuget package consolidation

### PR DESCRIPTION
**Pull request by honfika**
Doneness:
- [X] Build is okay - I made sure that this change is building successfully.
- [X] No Bugs - I made sure that this change is working properly as expected. It doesn't have any bugs that you are aware of. 
- [X] Branching - If this is not a hotfix, I am making this request against the master branch

### CODE REVIEW

**Comment by honfika** [comment]
There are 2 dependent nuget packages which can't be upgraded:
Microsoft.Win32.Registry and System.Security.Principal.Windows

Because the newer version of that packages requires .net 4.6+

It blocks the TWP users to update those packages in their projects (in case they are using them)

.net 4.5 and 4.5.1 is not supported anymore.
However .net 4.5.2 is still supported until 2023...

Anyway, it seems that microsoft is not supporting .net 4.5.x in their own newer nuget packages, so what do you think about setting the .net requirement to 4.6?

**Comment by honfika** [comment]
Or 4.6.1, which is .net standard 2.0.

Some popular nuget packages are also requiring .net 4.6.1+, for example: https://www.nuget.org/packages/AutoMapper/

**Comment by justcoding121** [comment]
We can add another separate build for .net 4.6.1 in addition to .net 4.5 packages we have now. So our NuGet package would be available in .Net 4.5 and .net 4.6, while 4.5 will have the minor issue you mentioned above.

**Comment by honfika** [comment]
Just noticed that those 2 packages are referenced only in the netstandard and netcore builds. (It seems that VS nuget update UI does not support conditional references). So net46 is not needed.

**Pull request merged**
