### PR TITLE
Added property for proxyRunning flag.

### PR DESCRIPTION
**Pull request by aricih**
* IP Helper API is wrapped & ProcessId property added to HttpWebClient class.
* A getter only property for proxyRunning flag is added to read the current state of ProxyServer.

### CODE REVIEW

**Comment by justcoding121** [comment]
Was this good to go? 

This was targeting release branch, which is what we want to use for new features.

Any changes in this compared to #126. If not I can reopen and merge this.

**Comment by aricih** [comment]
Yes it was. There was a complication in my fork, I've accidentially deleted release branch in my fork. I'll create a new PR asap. 

P.S.; It's @aricih :)

**Comment by ArachisH** [comment]
Hi

**Comment by justcoding121** [comment]
I see. So this is your new account.

**Comment by aricih** [comment]
It's a new account of mine that part is true but I'm not @ArachisH :)

Hey @ArachisH, please tell you're not me :)

**Comment by ArachisH** [comment]
I'm not @aricih, :(

**Pull request closed without merging**
