### PR TITLE
Let introduce the request state to keep it between events and simplify error logging.

### PR DESCRIPTION
**Pull request by volanavlad**
See basic sample

Doneness:
- [*] Build is okay - I made sure that this change is building successfully.
- [*] No Bugs - I made sure that this change is working properly as expected. It doesn't have any bugs that you are aware of. 
- [*] Branching - If this is not a hotfix, I am making this request against the master branch

### CODE REVIEW

**Comment by honfika** [comment]
There is already a SessionEventArgs class, it contains the state of the request. I think it is unnecessary to add another object.

There are too many garbage in this PR, for example Titanium.Web.Proxy.Examples.Wpf_lmb5j4or_wpftmp.csproj file. It looks a temporary file.
Also a lot of merge commits and commits from other users. So it looks a little bit strange.

Why did you rename the ProxyServer class to ProxyServer base?

What do you want to achive exaclty?

**Comment by ByronAP** [comment]
💥 🏃  👀

**Comment by volanavlad** [comment]
SessionEventArgs is not extensible by custom state.

Moreover SessionEventArgs  is too late. I need to share state between all pipeline events, i.e. including

ServerCertificateValidationCallback;
ClientCertificateSelectionCallback;
OnClientConnectionCreate;
OnServerConnectionCreate;
onBeforeTunnelConnectRequest
onBeforeTunnelConnectResponse
multipartRequestPartSent
etc..

and of course I need to have access to my (custom, extended) state in error handler on any pipeline  stage including socket internal errors.

Yes, I have renamed old ProxyServer class to ProxyServer base to minimize changes in code.
But I provide new ProxyServer with exactly same public api.
You can see that all tests and 2 other examples works well with no changes in its code.

You can see at basic sample that all that you need to implement custom state is to inherit from base request state and all other things became work fine.

```
public class ExtendedProxyState : RequestState<ExtendedProxyState>
{
	// this is my custom state and I can use it anywhere including my custom error handlers below
	internal StringBuilder PipelineInfo=new StringBuilder();
 
	public override async Task OnErrorAsync(Exception e)
	{
		await Console.Out.WriteLineAsync($"OnErrorAsync: {PipelineInfo} : {e}");
	}
	public override void OnError(Exception e)
	{
		Console.Out.WriteLine($"OnErrorAsync: {PipelineInfo}: {e}");
	}
}
// new proxy server with extended state but the same public API - no other coding need 
public class ProxyServer : ExtendedProxyState.ProxyServer
{
}

```  

Please compile and debug Titanium.Web.Proxy.Examples.Basic sample at master branch in my fork.

I would make much more refactoring to simplify API but now I prefer to have code compatibility and simple merges with base repo.

**Comment by honfika** [comment]
> SessionEventArgs is not extensible by custom state.

There is a UserData property in the SessionEventArgs(Base) class. You can set any custom state in that.

SessionEventArgs was already there in:
BeforeTunnelConnectRequest
BeforeTunnelConnectResponse

It was just added to `ServerCertificateValidationCallback `and `ClientCertificateSelectionCallback `callbacks because of issue #460, and also added to MultipartRequestPartSent

I can add the user data to OnClientConnectionCreate event if needed.

OnServerConnectionCreate is not really related to a single session, since the connections are re-used for new client connections, however it could receive the first user data.

I'm sorry, but currently I can't merge this PR. Please try to create a new one only with your changes.
Now this PR is overwriting a lot of other changes, please check the compare:
https://github.com/justcoding121/Titanium-Web-Proxy/pull/690/files?w=1

And also please create a clean PR:
- as I already mentioned, there is a temproary csproj: Titanium.Web.Proxy.Examples.Wpf_lmb5j4or_wpftmp.csproj
- code formatting is not following the source of TWP
- add new line after }
- no new line before {
- space after comma in metgod arguents (and calls)
- no space before comma in metgod arguents (and calls)
- the ident was modified, for example check the ProxyTestController file:
https://github.com/justcoding121/Titanium-Web-Proxy/pull/690/commits/8a5cc3f842a46b02ac201285f132f69fdeadaeaf#diff-99a6447bc3706ce43dce200ee1f400e3
- there are merge problems for example in ProxyTestController writeToConsole method
- websocket example which was added yesterday was removed (probabaly merge problem)
- some code was just commented out, why? For example: //await @lock.WaitAsync();

**Comment by volanavlad** [comment]
No problem.
I will keep my own fork.

**Comment by volanavlad** [comment]
User state in ProxyEventArgsBase? May be it solve my critical needs rigth now. But what about socket errors? Before client connection is established? How to diagnose it?

I will try to show how to do it in my fork. You are welcome to merge my code any time.

**Comment by ByronAP** [comment]
How would you have a socket error before a client makes a request? A listener error?

**Comment by honfika** [comment]
A listen error can be catched when you call the ProxyServer.Start() method (Or the ProxyServer.AddEndPoint(), while the server is already running)

But I think there is no related changes for this in your fork.

Now the only differnece that I see is that you have an OnError method, which is only called when there is an exception in the User code of the ServerCertificateValidationCallback.

It is a good idea to add a non-global error handler to the request. I'll add it to the ProxyBaseEventArgs, so you will be able to subscribe for the errors of a single request. I plan to add an IsHandled property to the event arguments and when it is not true, the global error handler will be called (as it is now). And of course it should be fired for user calback errors and non user errors, too.

I appreciate your work, but next time if you create a PR, please be careful and do not overwrite other changes and do not reformat the code (using tabs), only when the purpuse of the PR is the code cleanup.

**Comment by volanavlad** [comment]
OK

**Comment by volanavlad** [comment]
Next time I will try to foollow code formatting of the source of TWP.

But you need to merge your beta and stable branches to master.
Otheewise you will always get garbage on any PR from other repos.

**Pull request closed without merging**
