### PR TITLE
Fixes and Demo app improvements

### PR DESCRIPTION
**Pull request by honfika**
Doneness:
- [x] Build is okay - I made sure that this change is building successfully.
- [x] No Bugs - I made sure that this change is working properly as expected. It doesn't have any bugs that you are aware of. 
- [x] Branching - If this is not a hotfix, I am making this request against develop branch

### CODE REVIEW

**Comment by justcoding121** [comment]
I feel like there is something wacky in this change I believe. For example the tests for web-sockets are no more working. Try following websites which used to pass.

https://www.websocket.org/echo.html
https://websocketstest.com/

**Comment by justcoding121** [comment]
Last stable version where websockets are working is at below revision.

https://github.com/justcoding121/Titanium-Web-Proxy/tree/72a9eda4a72c5a2f8c37809ea71184c39d76b59a

So may be we will have to look at the changes made after that.

**Comment by honfika** [comment]
I tried it, and it seems to with with the basic console demo program. Could you please confirm that it works with that?
In the another demo the problem is that I read the response body every time in the BeforeResponse event, and if there is no response, it throws an exception.

The exceptions from the user events should be handled in TWP, I'll make a PR for that.

**Comment by honfika** [comment]
Please check PR #282 .

Why is the response status code a string? It is always a number, it could be "int?".

**Comment by justcoding121** [comment]
I don't mind using a number. I believe the issue started after you changes on SendRaw method. And inside that specifically CopyAsync method changes. Because web-socket requests are relayed as you probably know. Look my screenshot below. TLS connection itself could not be tunneled. This is from Console example.

Meanwhile can you tell me how exactly the DataSent & DataReceived functions are to behave? 
Are they supposed to be called anytime data is sent to server or to client? In current implementations I don't think its behaving well.

image

**Pull request merged**
