### PR TITLE
Parse ssl extensions

### PR DESCRIPTION
**Pull request by honfika**
Doneness:
- [X] Build is okay - I made sure that this change is building successfully.
- [X] No Bugs - I made sure that this change is working properly as expected. It doesn't have any bugs that you are aware of. 
- [X] Branching - If this is not a hotfix, I am making this request against develop branch

### CODE REVIEW

**Comment by justcoding121** [comment]
This is some good work. I believe the parsing of SSL extensions can be used to peek the **server_name** data for Transparent Endpoint. This will fix the long standing issue. Since their is no tunnel request in transparent endpoint as of now the way we peek the extensions probably need to be tweaked so that we can use it for its current purpose as well. Particularly the method `HttpsTools.IsClientHello`  should work without a second parameter type called `TunnelConnectSessionEventArguments`. 

https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Titanium.Web.Proxy/RequestHandler.cs#L217

**Comment by justcoding121** [comment]
By the way, a way to test Transparent Endpoint would be to call the [Transparent Endpoint](https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Titanium.Web.Proxy/RequestHandler.cs#L202) method[ right after sending successful connect response ](https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Titanium.Web.Proxy/RequestHandler.cs#L118)from Explicit Endpoint handler.

**Comment by honfika** [comment]
In PR #290 I refactored it a little bit, moved it to the Ssl folder, and renamed it to SslTools.
Now SslTools.IsClientHello works without the 2nd session arguments parameter.

And you can get the hostname with the following 2 lines:
```
var clientHelloInfo = await HttpsTools.GetClientHelloInfo(clientStream);
string hostName = clientHelloInfo?.Extensions.FirstOrDefault(x => x.Value == 0)?.Data;

```

I'll plan to do the same for ServerHello, but I can't promise it for this week.

**Comment by justcoding121** [comment]
Okay. That would be great. I will add the change on transparent endpoint to start supporting Server Name Indication.

I wonder if we can also do ALPN extension support by doing a small hack here. That would help us to jump start working on HTTP/2, since almost all servers use ALPN along with HTTP/2 over TLS. Currently I don't see ALPN support going to be added to SslStream anytime soon. 

https://github.com/dotnet/corefx/issues/4721

I haven't done much research, but in my understanding all we need to is to add the ALPN extension in client hello and read the selected protocol from server hello extension. So if we can read server hello, then the difficulty would be inserting the ALPN extension to the client hello. May be it can be done by using our own insert stream (like peek stream) over the server buffered stream. So when we call AuthenticateAsClient, we will pass our insert stream to modify the client hello before sending it to server.

**Pull request merged**
