### PR TITLE
IP Helper API wrapped to associate port with process id

### PR DESCRIPTION
**Pull request by aricih**
* ProxyRunning property is added to ProxyServer class.
* IP Helper API 'GetExtendedTcpTable' method and relevant structures are wrapped.
* ProcessId property is added to HttpWebClient class.

### CODE REVIEW

**Comment by justcoding121** [comment]
@aricih I approved and merged thinking that this goes to release branch. Can you please recreate this PR to release branch?

**Comment by aricih** [comment]
OK, thanks! I'll recreate PR to release branch ASAP.

**Comment by aricih** [comment]
You've reverted the changes in master branch, is something wrong? Btw, in release branch certificate management is buggy. It creates certificates but somehow doesn't install. That's why I moved my changes back to master branch, fyi.

**Comment by justcoding121** [comment]
@ilushka85 Can you take a look. I did try the merged beta branch in my machine and it didn't create & install root certificate as prev versions used to, even after running as admin.

**Comment by justcoding121** [comment]
@aricih Nothing was wrong. We want to add new features to release branch, and then once it reported to be stable we merge it to master.

Regarding the bug below comment may be helpful
https://github.com/justcoding121/Titanium-Web-Proxy/pull/123#issuecomment-249850190

**Comment by ilushka85** [comment]
It won't install root cert to machine store.  Just saves file locally.

**Comment by justcoding121** [comment]
@ilushka85 We would need to add that capability. 

If root certificate name is not provided by user, then we need to create a default root and install it.

If root certificate name is provided by user we find that certificate and use it to generate certificates.

That's how it was before.

**Comment by aricih** [comment]
@justcoding121 sorry I thought it was the other way around, so I've moved my changes to master branch.

@ilushka85 as @justcoding121 said, in master branch the certificate is also installed as soon as it's created, could you help us with that please?

**Comment by ilushka85** [comment]
So perhaps we should have a separate function that installs in root store. What is the purpose of always doing this ?

**Comment by aricih** [comment]
@ilushka85 without installing it the user will keep getting certificate not trusted error. IMHO, there should be both install and uninstall certificate functionalities so that created certificate could be installed in trusted root store whenever it's needed then it could be removed when it's no longer needed.

**Comment by ilushka85** [comment]
Yes but the cert is in local folder so user can install and uninstall already.  I just don't see why a proxy server should auto install locally if it's meant to accept remote connections.  It's only relevant and helpful for local connections.

**Comment by aricih** [comment]
User should not be dealing with this stuff. Just think about Fiddler, does it say here's your certificate please install it in a trusted store that you see fit? No, it installs its certificate to proper stores then it removes them after it's done with them. It works the same way in FiddlerCore too.

**Comment by ilushka85** [comment]
Sure but fiddler is a very specific application and even provides a UI to install these certs for users.  This proxy server is more of a component to be integrated into something for various use cases.  It should be up to the implementing program and use case to handle installing the certificate for a user if it's something needed.

**Comment by aricih** [comment]
I'm not saying that proxy should install the certificate everytime it's constructed. I'm saying it just should be able to do it when it's needed. Infact it was able to do it previously and in master branch it still is. We are aiming to use Titanium in our application (take a look at Netsparker), sure we can handle certificate installation in our fork but IMHO it will be needed by others too. It's up to @justcoding121, if this feature won't be in release branch we'll be managing our own fork. Thanks for your patience.

**Comment by justcoding121** [comment]
@ilushka85 I agree with @aricih . We try to accommodate the most common use cases. Most users are not aware of the intricacies of the whole certificate chain. Likely many will use this for local traffic interception, which is what fiddlercore is also doing. They likely want to intercept not just HTTP traffic, they would also like to see secure HTTPS traffic immediately upon installation of this library.

But it is not enforced strictly. The proxy should have an option to use custom certificate, if not then it should by default install and use it. That's how it is now, and if not users are going to complain once released.

**Comment by justcoding121** [comment]
@aricih I will try to include this feature in @ilushka85 code this weekend. 

If its too difficult, I may need to revert the #123 merge and then merge your changes for process Id. But the problem is bug #122 . I am pretty sure there is a way to fix it, given fiddlercore is also using makecert without any deadlocks. There is a performance gain as @ilushka85 mentioned in his change, but I am not sure if it is significant. If I recall right, I have observed certificates get generated within 50ms  from makecert. Also #123 mentions an issue with permissions which is also a problem.

**Comment by ilushka85** [comment]
The permissions issue is actually fine with latest changes fiddlercore moved away from makecert as well.  The 50ms does not seem like a lot until you are pumping thousands of simultaneous requests thru.

**Comment by ilushka85** [comment]
I'll add back the install to store code. It's pretty simple.  Will be ready on Monday.

**Pull request merged**
