### PR TITLE
Fix for #289

### PR DESCRIPTION
**Pull request by honfika**
Doneness:
- [X] Build is okay - I made sure that this change is building successfully.
- [X] No Bugs - I made sure that this change is working properly as expected. It doesn't have any bugs that you are aware of. 
- [X] Branching - If this is not a hotfix, I am making this request against develop branch 

I tried it with no upstream proxy, with local upstream proxy without authentication, and a remote proxy with authentication. They seems to work.

### CODE REVIEW

**Comment by justcoding121** [comment]
I am trying to understand the change here. So this change allows both HTTP & HTTPS upstream proxy with authorization? Where are we sending the username/password to server for HTTP. I see only for HTTPS. 

https://github.com/honfika/Titanium-Web-Proxy/blob/2d2755c65230e9fded434f689d9a0b8b96796686/Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs#L77

**Comment by justcoding121** [comment]
So this allows HTTPS client => HTTP/HTTPS upstream proxy. Will it work for HTTP client => HTTP/HTTPS upstream proxy? I am confused.

**Comment by chancity** [comment]
Rename useProxy to useUpStreamProxy?

Looks like he consolidated HTTP and HTTPS up stream proxy to a single up stream proxy.

**Comment by honfika** [comment]
@justcoding121 the HTTP authentication is in the HttpWebClient.SendRequest
So in the TcpConnectionFactory it is needed only for HTTPS

**Comment by honfika** [comment]
HTTP requests are forwarded to UpStreamHttpProxy, HTTPS requests are forwarded to UpStreamHttpsProxy.

**Pull request merged**
