### PR TITLE
Create proper support for Upstream proxy supporting username, passwor…

### PR DESCRIPTION
**Pull request by ilushka85**
…d, and ssl fixes

### CODE REVIEW

**Comment by ilushka85** [comment]
Add support for passing a function to figure out a per request based proxy

**Comment by ilushka85** [comment]
Now we can support authentication if a func is passed in for both http and https requets.  Supports basic authentication

**Comment by justcoding121** [comment]
@ilushka85 Good work. Can you fix merge conflicts please. I don't want to merge this to master. Lets do a beta release by committing to release branch.

**Comment by ilushka85** [comment]
Just merged in release and fixed the conflicts.  Also added some more params to SessionEventArgs

**Pull request merged**
